#!/bin/bash

NUMBER=0
SHOWCONTENTS=0
SHOWHELP=0

mkdir -p ~/.junk

if [ $# == 0 ]
then
    echo "Missing arguments!"
    exit 1
fi

for i  in "$@"
do
case $i in
    -l)
    SHOWCONTENTS=1
    ;;

    -n)
    NUMBER=1
    ;;

    --help)
    SHOWHELP=YES
    ;;

    *)
    if [ $i -nt ~/.junk/$i ]
    then
        mv $i ~/.junk
    fi
    ;;
esac
done

if [ $SHOWCONTENTS == 1 ]
then
    ls -la ~/.junk
fi
if [ $NUMBER == 1 ]
then
    du -ah ~/.junk
fi
